from enum import Enum

class AppConfiguration(Enum):
    SQLALCHEMY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
    SQLALCHEMY_TRACK_MODIFICATIONS = "SQLALCHEMY_TRACK_MODIFICATIONS"
    ENVIRONMENT = "ENV"
    DEBUG = "DEBUG"
    HOST = 'HOST'
    PORT = 'PORT'
